//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunStokOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBUrunStokEntities : DbContext
    {
        public DBUrunStokEntities()
            : base("name=DBUrunStokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLDUYURU> TBLDUYURU { get; set; }
        public virtual DbSet<TBLSATISHAREKET> TBLSATISHAREKET { get; set; }
        public virtual DbSet<TBLURUN> TBLURUN { get; set; }
        public virtual DbSet<TBLUYE> TBLUYE { get; set; }
    
        public virtual ObjectResult<string> EnCokSatilanUrun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnCokSatilanUrun");
        }
    
        public virtual int EnCokSatisYapanUye()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnCokSatisYapanUye");
        }
    
        public virtual ObjectResult<Nullable<double>> TukenenBademKilosu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("TukenenBademKilosu");
        }
    
        public virtual ObjectResult<Nullable<double>> TukenenBiberKilosu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("TukenenBiberKilosu");
        }
    
        public virtual ObjectResult<Nullable<double>> TukenenFistikKilosu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("TukenenFistikKilosu");
        }
    
        public virtual ObjectResult<string> EnCokSatanUye()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnCokSatanUye");
        }
    }
}
