//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunStokOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLDUYURU
    {
        public int? ID { get; set; }

        [Required(ErrorMessage = "Konu alaný zorunludur.")]
        [StringLength(maximumLength: 50, ErrorMessage = "50 karakterden uzun konu olamaz.", MinimumLength = 2)]
        public string KONU { get; set; }

        [Required(ErrorMessage = "Ýçerik alaný zorunludur.")]
        public string ICERIK { get; set; }

        [Required(ErrorMessage = "Tarih alaný zorunludur.")]
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
