//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunStokOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLURUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLURUN()
        {
            this.TBLSATISHAREKET = new HashSet<TBLSATISHAREKET>();
        }

        public int? ID { get; set; }

        [Required(ErrorMessage = "Ad alaný zorunludur.")]
        [StringLength(maximumLength: 50, ErrorMessage = "Adýnýzýn uzunluðunu kontrol ediniz.", MinimumLength = 2)]
        [RegularExpression(@"^(([A-za-z]+[\s]{1}[A-za-z]+)|([A-Za-z]+))$", ErrorMessage = "Lütfen yanlýzca büyük-küçük harf giriniz.")]
        public string AD { get; set; }

        [Required(ErrorMessage = "Fiyat alaný zorunludur.")]
        public Nullable<double> FIYAT { get; set; }
        public string DETAY { get; set; }
        public Nullable<bool> DURUM { get; set; }

        [Required(ErrorMessage = "Stok alaný zorunludur.")]
        [Range(0,99999,ErrorMessage = "Stok deðeri negatif deðer girilemez.")]
        public Nullable<double> STOK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATISHAREKET> TBLSATISHAREKET { get; set; }
    }
}
