//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunStokOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLUYE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUYE()
        {
            this.TBLSATISHAREKET = new HashSet<TBLSATISHAREKET>();
        }
    
        public int? ID { get; set; }

        [Required(ErrorMessage = "Ad alaný zorunludur.")]
        [StringLength(maximumLength: 50, ErrorMessage = "Adýnýzýn uzunluðunu kontrol ediniz.", MinimumLength = 2)]      
        public string AD { get; set; }

        [Required(ErrorMessage = "Soyad alaný zorunludur.")]
        [StringLength(maximumLength: 50, ErrorMessage = "Soyadýnýzýn uzunluðunu kontrol ediniz.", MinimumLength = 2)]       
        public string SOYAD { get; set; }

        [Required(ErrorMessage = "Kullanýcý adý alaný zorunludur.")]
        [StringLength(maximumLength: 20, ErrorMessage = "Kullanýcý adýnýz 4 ile 20 karakter uzunluðunda olmalýdýr.", MinimumLength = 4)]
        public string KULLANICIADI { get; set; }

        [Required(ErrorMessage = "Þifre alaný zorunludur.")]
        [StringLength(maximumLength: 20, ErrorMessage = "Þifreniz 6 ile 20 karakter uzunluðunda olmalýdýr.", MinimumLength = 6)]
        public string SIFRE { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATISHAREKET> TBLSATISHAREKET { get; set; }
    }
}
